#!/usr/bin/env node
// Read .env, ensure the R2 bucket and KV namespace exist, then substitute
// ${PLACEHOLDER} tokens in wrangler.example.jsonc into wrangler.jsonc.
//
// Idempotent — safe to re-run. No npm dependencies; uses only Node built-ins.
// All shell-outs go through execFileSync (no shell interpolation) so values
// pulled from .env can't be turned into command injection.

import { readFileSync, writeFileSync, existsSync, appendFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const ROOT = join(SCRIPT_DIR, "..");
const ENV_PATH = join(ROOT, ".env");
const TEMPLATE_PATH = join(ROOT, "wrangler.example.jsonc");
const OUT_PATH = join(ROOT, "wrangler.jsonc");

const REQUIRED = ["CLOUDFLARE_ACCOUNT_ID", "MCP_HOSTNAME", "R2_BUCKET_NAME"];

function parseEnv(text) {
  const out = {};
  for (const raw of text.split("\n")) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq < 0) continue;
    const key = line.slice(0, eq).trim();
    let val = line.slice(eq + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    out[key] = val;
  }
  return out;
}

function runWrangler(args) {
  return execFileSync("npx", ["wrangler", ...args], {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
  });
}

function ensureR2Bucket(name) {
  process.stdout.write(`R2 bucket "${name}"... `);
  try {
    runWrangler(["r2", "bucket", "create", name]);
    console.log("created");
  } catch (e) {
    const msg = String(e.stderr || e.message || "").toLowerCase();
    if (msg.includes("already exists") || msg.includes("bucketalreadyowned")) {
      console.log("already exists");
      return;
    }
    console.log("FAILED");
    console.error(e.stderr || e.message);
    process.exit(1);
  }
}

function ensureKvNamespace(env) {
  if (env.OAUTH_KV_ID) {
    console.log(`KV namespace OAUTH_KV: ${env.OAUTH_KV_ID} (from .env)`);
    return;
  }
  process.stdout.write(`KV namespace OAUTH_KV... `);
  let out;
  try {
    out = runWrangler(["kv", "namespace", "create", "OAUTH_KV"]);
  } catch (e) {
    console.log("FAILED");
    console.error(e.stderr || e.message);
    process.exit(1);
  }
  // Wrangler output contains either `id = "..."` or `"id": "..."` depending
  // on version; accept both. KV ids are 32 hex chars.
  const m = out.match(/(?:id\s*[=:]\s*"?|"id"\s*:\s*")([0-9a-f]{32})"?/);
  if (!m) {
    console.log("FAILED");
    console.error("could not parse KV namespace id from wrangler output:");
    console.error(out);
    process.exit(1);
  }
  const id = m[1];
  console.log(`created (${id})`);
  appendFileSync(ENV_PATH, `\n# auto-filled by scripts/setup.mjs\nOAUTH_KV_ID=${id}\n`);
  env.OAUTH_KV_ID = id;
}

function applyDefaults(env) {
  if (env.VAULT_PREFIX === undefined) env.VAULT_PREFIX = "";
  if (env.DAILY_NOTE_PATH_TEMPLATE === undefined) env.DAILY_NOTE_PATH_TEMPLATE = "Daily Notes/{{YYYY-MM-DD}}.md";
  if (env.PERMALINK_BASE_URL === undefined) env.PERMALINK_BASE_URL = "";
  // Default-closed: empty means upload_attachment_url can fetch from no host.
  if (env.ATTACHMENT_FETCH_HOST_ALLOWLIST === undefined) env.ATTACHMENT_FETCH_HOST_ALLOWLIST = "";
}

function verifyAccount(accountId) {
  process.stdout.write(`wrangler auth... `);
  let whoami;
  try {
    whoami = runWrangler(["whoami"]);
  } catch (e) {
    console.log("FAILED");
    console.error("`npx wrangler whoami` failed — run `npx wrangler login` first.");
    process.exit(1);
  }
  if (!whoami.includes(accountId)) {
    console.log("WRONG ACCOUNT");
    console.error(`Expected account id ${accountId} but wrangler is logged into a different one.`);
    console.error(`Run \`npx wrangler logout && npx wrangler login\` and pick the correct account.`);
    process.exit(1);
  }
  console.log(`account ${accountId}`);
}

function main() {
  if (!existsSync(ENV_PATH)) {
    console.error("error: .env not found.");
    console.error("       cp .env.example .env, then edit .env to fill in your values.");
    process.exit(1);
  }
  if (!existsSync(TEMPLATE_PATH)) {
    console.error(`error: ${TEMPLATE_PATH} not found.`);
    process.exit(1);
  }

  const env = parseEnv(readFileSync(ENV_PATH, "utf8"));
  applyDefaults(env);

  const missing = REQUIRED.filter((k) => !env[k]);
  if (missing.length) {
    console.error(`error: .env is missing required values: ${missing.join(", ")}`);
    process.exit(1);
  }

  verifyAccount(env.CLOUDFLARE_ACCOUNT_ID);
  ensureR2Bucket(env.R2_BUCKET_NAME);
  ensureKvNamespace(env);

  let out = readFileSync(TEMPLATE_PATH, "utf8");
  out = out.replace(
    /^(\/\/[^\n]*\n)+/,
    "// Generated by scripts/setup.mjs from wrangler.example.jsonc + .env.\n" +
    "// Edit .env and rerun `npm run setup` rather than editing this file.\n",
  );
  out = out.replace(/\$\{([A-Z_][A-Z0-9_]*)\}/g, (match, key) => {
    if (!(key in env)) {
      console.error(`error: template references \${${key}} but .env has no such key.`);
      process.exit(1);
    }
    return env[key];
  });

  writeFileSync(OUT_PATH, out);
  console.log(`wrote ${OUT_PATH}`);
  console.log("");
  console.log("next steps:");
  console.log("  1. npx wrangler secret put AUTH_PASSWORD   # set OAuth password (first time only)");
  console.log("  2. npm test                                 # verify");
  console.log("  3. npx wrangler deploy                      # deploy");
}

main();
